/* eslint-disable jsx-a11y/alt-text */
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="text-gray-600 body-font shadow-lg ">
        <div className="container mx-auto flex flex-wrap p-[1.5rem] flex-col md:flex-row items-center">
          <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            {/* <Image src={'/logo.jpg'} width={'10'} height={'10'}></Image > planning to add image to the navbar */}
            {/* use color for lime or red or green or lime or emerald or sky */}
            <span className=" ml-3 text-xl">CompanyName</span>
          </a>
          <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center">
            <a className="mr-5 hover:text-emerald-500 font-bold cursor-pointer">Home</a>
            <a className="mr-5 hover:text-emerald-500 font-bold cursor-pointer">Shop</a>
            {/* <a className="mr-5 hover:text-emerald-500 font-bold cursor-pointer"></a> */}
            <a className="mr-5 hover:text-emerald-500 font-bold cursor-pointer">Contact</a>
          </nav>
        </div>
      </header>
    </div>
  )
}
